
interface Translations {
  [key: string]: string;
}

// English translations - all keys return English values
const enTranslations: Translations = {
  mining: 'Mining',
  tasks: 'Tasks', 
  wallet: 'Wallet',
  friends: 'Friends',
  settings: 'Settings',
  store: 'Store',
  leaderboard: 'Leaderboard',
  more: 'More',
  mainTasks: 'Main Tasks',
  partnerTasks: 'Partner Tasks',
  dailyTasks: 'Daily Tasks',
  connectWallet: 'Connect Wallet',
  connectWalletDesc: 'Connect your wallet to start mining',
  firstMine: 'First Mine',
  firstMineDesc: 'Complete your first mining operation',
  completeProfile: 'Complete Profile',
  completeProfileDesc: 'Complete your profile information',
  joinTelegram: 'Join Telegram',
  joinTelegramDesc: 'Join our Telegram channel',
  followTwitter: 'Follow Twitter',
  followTwitterDesc: 'Follow our Twitter account',
  subscribeYoutube: 'Subscribe YouTube',
  subscribeYoutubeDesc: 'Subscribe to our YouTube channel',
  dailyLogin: 'Daily Login',
  dailyLoginDesc: 'Complete your daily login',
  dailyMine: 'Daily Mine',
  dailyMineDesc: 'Complete your daily mining',
  dailyShare: 'Daily Share',
  dailyShareDesc: 'Share the app daily',
  taskCompleted: 'Task Completed',
  earnedReward: 'You earned',
  completeTasksEarn: 'Complete tasks and earn $SPACE coins',
  receiveCoins: 'Receive Coins',
  walletAddress: 'Wallet Address',
  shareAddressInstruction: 'Share this address to receive coins',
  copied: 'Copied',
  walletAddressCopied: 'Wallet address copied to clipboard',
  copyAddress: 'Copy Address',
  lastWinner: 'Last Winner',
  prize: 'Prize',
  time: 'Time',
  progress: 'Progress',
  currentTicket: 'Current Ticket',
  ticketCollection: 'Ticket Collection',
  surpriseBonus: 'Surprise Bonus!',
  awesome: 'Awesome!',
  claimTicket: 'Claim Ticket',
  getFreeTicket: 'Get Free Ticket',
  buyTicket: 'Buy Ticket',
  processing: 'Processing...',
  claimed: 'Claimed',
  dailyRush: 'Daily Rush',
  collect: 'Collect',
  win: 'Win',
  earn: 'Earn',
  dailyLoginStreak: 'Daily Login Streak',
  loginDaily: 'Log in daily to earn increasing rewards!',
  streakBroken: 'Streak Broken!',
  startingFresh: 'Starting fresh from Day 1',
  currentStreak: 'Current Streak',
  resetIn: 'Reset in:',
  claimDailyReward: 'Claim Daily Reward',
  claimedToday: 'Claimed Today!',
  totalSpaceEarned: 'Total $SPACE Earned',
  totalTicketsEarned: 'Total Tickets Earned',
  weekCompleteBonus: 'Week Complete Bonus!',
  earnedTonBonus: 'You earned 0.1 TON for completing a full week!',
  error: 'Error',
  success: 'Success',
  taskCompletedMessage: 'Task completed successfully',
  youEarned: 'You earned',
  coins: 'coins',
  taskCompleteError: 'Failed to complete task',
  pleaseLoginFirst: 'Please login first',
  loadingTasks: 'Loading tasks...',
  completeTasksEarnRewards: 'Complete tasks and earn rewards',
  noMainTasks: 'No main tasks available',
  noPartnerTasks: 'No partner tasks available',
  noDailyTasks: 'No daily tasks available',
  startMining: 'Start Mining',
  premiumStore: 'Premium Store',
  spaceCoins: 'SPACE Coins',
  premiumSubscriptions: 'Premium Subscriptions',
  powerBoosts: 'Power Boosts',
  premiumBenefits: 'Premium Benefits',
  enhanceExperience: 'Enhance your mining experience',
  unlockFeatures: 'Unlock faster mining speeds, exclusive features, and maximize your earning potential',
  buyNow: 'Buy Now',
  subscribe: 'Subscribe',
  active: 'Active',
  walletRequired: 'Wallet Required',
  connectWalletFirst: 'Connect your TON wallet first',
  purchaseSuccessful: 'Purchase Successful!',
  purchaseFailed: 'Purchase Failed',
  paymentTransactionFailed: 'Payment transaction failed',
  // Daily Rush specific translations
  dailyRushEvent: 'Daily Rush Event',
  collectTicketsWinRewards: 'Collect tickets and win amazing rewards!',
  todaysWinner: "Today's Winner",
  timeRemaining: 'Time Remaining',
  overallProgress: 'Overall Progress',
  rushTickets: 'Rush Tickets',
  milestoneBonuses: 'Milestone Bonuses',
  surpriseBonusReceived: 'You\'ve received surprise bonuses!',
  ticketClaimed: 'Ticket Claimed!',
  cannotClaimTicket: 'Cannot Claim Ticket',
  loadingDailyRush: 'Loading Daily Rush...',
  failedToLoadEvent: 'Failed to load Daily Rush event',
  failedToClaimTicket: 'Failed to claim ticket',
  free: 'FREE',
  locked: 'Locked',
  pending: 'Pending'
};

const getCurrentLanguage = (): string => {
  return 'en'; // Always return English
};

export const getTranslation = (key: string): string => {
  // Return the translation if it exists, otherwise return the key itself
  const translation = enTranslations[key];
  return translation || key;
};

export const setLanguage = (language: string) => {
  // Do nothing - always use English
};
